service:
  info:
    name: jsboard
    version: 1.0.0
    
logging:
  level:
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.springframework.data: INFO
    
---
spring.profiles: server

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hansonlab;MVCC=TRUE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org.springframework.web: INFO